### ISSUE TITLE
Class "tool_emailutils\advanced_testcase" not found

### ISSUE THREAD

**Issue by golenkovm** [catalyst/moodle-tool_emailutils#47]
Unit tests are broken in Moodle 4.4:
```
Moodle 4.4.3+ (Build: 20240910)
Php: 8.1.2.1.2.18, pgsql: 14.13 (Debian 14.13-1.pgdg120+1), OS: Linux 6.5.0-1024-aws x86_64

Fatal error: Uncaught Error: Class "tool_emailutils\advanced_testcase" not found in /var/www/site/admin/tool/emailutils/tests/suffix_test.php:27
Stack trace:
#0 /var/www/site/vendor/phpunit/phpunit/src/Util/FileLoader.php(66): include_once()
#1 /var/www/site/vendor/phpunit/phpunit/src/Util/FileLoader.php(49): PHPUnit\Util\FileLoader::load('/var/www/site/a...')
#2 /var/www/site/vendor/phpunit/phpunit/src/Framework/TestSuite.php(398): PHPUnit\Util\FileLoader::checkAndLoad('/var/www/site/a...')
#3 /var/www/site/vendor/phpunit/phpunit/src/Framework/TestSuite.php(537): PHPUnit\Framework\TestSuite->addTestFile('/var/www/site/a...')
#4 /var/www/site/vendor/phpunit/phpunit/src/TextUI/TestSuiteMapper.php(67): PHPUnit\Framework\TestSuite->addTestFiles(Array)
#5 /var/www/site/vendor/phpunit/phpunit/src/TextUI/Command.php(393): PHPUnit\TextUI\TestSuiteMapper->map(Object(PHPUnit\TextUI\XmlConfiguration\TestSuiteCollection), '')
#6 /var/www/site/vendor/phpunit/phpunit/src/TextUI/Command.php(114): PHPUnit\TextUI\Command->handleArguments(Array)
#7 /var/www/site/vendor/phpunit/phpunit/src/TextUI/Command.php(99): PHPUnit\TextUI\Command->run(Array, true)
#8 /var/www/site/vendor/phpunit/phpunit/phpunit(107): PHPUnit\TextUI\Command::main()
#9 /var/www/site/vendor/bin/phpunit(122): include('/var/www/site/v...')
#10 {main}

Next PHPUnit\TextUI\RuntimeException: Class "tool_emailutils\advanced_testcase" not found in /var/www/site/vendor/phpunit/phpunit/src/TextUI/Command.php:101
Stack trace:
#0 /var/www/site/vendor/phpunit/phpunit/phpunit(107): PHPUnit\TextUI\Command::main()
#1 /var/www/site/vendor/bin/phpunit(122): include('/var/www/site/v...')
#2 {main}
  thrown in /var/www/site/vendor/phpunit/phpunit/src/TextUI/Command.php on line 101
PHP Fatal error:  Uncaught Error: Class "tool_emailutils\advanced_testcase" not found in /var/www/site/admin/tool/emailutils/tests/suffix_test.php:27
Stack trace:
#0 /var/www/site/vendor/phpunit/phpunit/src/Util/FileLoader.php(66): include_once()
#1 /var/www/site/vendor/phpunit/phpunit/src/Util/FileLoader.php(49): PHPUnit\Util\FileLoader::load('/var/www/site/a...')
#2 /var/www/site/vendor/phpunit/phpunit/src/Framework/TestSuite.php(398): PHPUnit\Util\FileLoader::checkAndLoad('/var/www/site/a...')
#3 /var/www/site/vendor/phpunit/phpunit/src/Framework/TestSuite.php(537): PHPUnit\Framework\TestSuite->addTestFile('/var/www/site/a...')
#4 /var/www/site/vendor/phpunit/phpunit/src/TextUI/TestSuiteMapper.php(67): PHPUnit\Framework\TestSuite->addTestFiles(Array)
#5 /var/www/site/vendor/phpunit/phpunit/src/TextUI/Command.php(393): PHPUnit\TextUI\TestSuiteMapper->map(Object(PHPUnit\TextUI\XmlConfiguration\TestSuiteCollection), '')
#6 /var/www/site/vendor/phpunit/phpunit/src/TextUI/Command.php(114): PHPUnit\TextUI\Command->handleArguments(Array)
#7 /var/www/site/vendor/phpunit/phpunit/src/TextUI/Command.php(99): PHPUnit\TextUI\Command->run(Array, true)
#8 /var/www/site/vendor/phpunit/phpunit/phpunit(107): PHPUnit\TextUI\Command::main()
#9 /var/www/site/vendor/bin/phpunit(122): include('/var/www/site/v...')
#10 {main}

Next PHPUnit\TextUI\RuntimeException: Class "tool_emailutils\advanced_testcase" not found in /var/www/site/vendor/phpunit/phpunit/src/TextUI/Command.php:101
Stack trace:
#0 /var/www/site/vendor/phpunit/phpunit/phpunit(107): PHPUnit\TextUI\Command::main()
#1 /var/www/site/vendor/bin/phpunit(122): include('/var/www/site/v...')
#2 {main}
  thrown in /var/www/site/vendor/phpunit/phpunit/src/TextUI/Command.php on line 101
```

At the first glance it looks to be a regression of https://github.com/catalyst/moodle-tool_emailutils/commit/25871da3561b95c00407de6b2b6644ae9bf702e5

**Comment by brendanheywood** [comment]
The task here is to 

1) add support for 4.4 in the version / matrix
2) then fix bug

OR

if we need to make a new stable branch. If we can avoid it then better, its likely we will need a new stable at 4.5 lts anyway
